In [13]:
import pandas as pd
from pymatgen.core.periodic_table import Element 
import numpy as np

In [14]:
df = pd.DataFrame(columns=['A','B1','B2','X','AB1B2X'], index=np.arange(36))

n = 0
for A in ['K','Rb','Cs']:
    for B1 in ['In','Tl']:
        for B2 in ['In','Tl']:
            for X in ['Cl','Br','I']:
                df.iloc[n, 0] = A
                df.iloc[n, 1] = B1
                df.iloc[n, 2] = B2
                df.iloc[n, 3] = X
                df.iloc[n, 4] = A + B1 + B2 + X
                n = n+1

In [15]:
def get_finished():
    A=['K','Rb','Cs']
    B=['Ag','Cu','K','Na','Li']
    C=['Bi','Sb','Ce','Pr','Nd','Ta','Mo','Y']
    D=['F','Cl','Br','I']
    list1 = []
    for a in A:
        for b in B:
            for c in C:
                for d in D:
                    list1.append(a+b+c+d)
                    
                    
    with open('/Users/yao/Google Drive/data/2116/screen_list_Cl','r') as f:
        for line in f:
            list1.append(line.split(' ')[0]+line.split(' ')[1]+line.split(' ')[2]+line.split(' ')[3].replace('\n', ''))
            
    with open('/Users/yao/Google Drive/data/2116/screen_list_FBrI','r') as f:
        for line in f:
            list1.append(line.split(' ')[0]+line.split(' ')[1]+line.split(' ')[2]+line.split(' ')[3].replace('\n', ''))
            
    with open('/Users/yao/Google Drive/data/2116/screen_list_remaining_wo_transition_metal','r') as f:
        for line in f:
            list1.append(line.split(' ')[0]+line.split(' ')[1]+line.split(' ')[2]+line.split(' ')[3].replace('\n', ''))
            
    return set(list1)

In [16]:
compute_df = df[~df['AB1B2X'].isin(get_finished())]

In [20]:
compute_df.to_csv('/Users/yao/Google Drive/data/2116/screen_list_InTl', \
                  sep=' ',columns=['A','B1','B2','X'],  header=False, index=False)

In [19]:
compute_df

     A  B1  B2   X    AB1B2X
0    K  In  In  Cl   KInInCl
1    K  In  In  Br   KInInBr
2    K  In  In   I    KInInI
3    K  In  Tl  Cl   KInTlCl
4    K  In  Tl  Br   KInTlBr
5    K  In  Tl   I    KInTlI
8    K  Tl  In   I    KTlInI
9    K  Tl  Tl  Cl   KTlTlCl
11   K  Tl  Tl   I    KTlTlI
12  Rb  In  In  Cl  RbInInCl
13  Rb  In  In  Br  RbInInBr
14  Rb  In  In   I   RbInInI
15  Rb  In  Tl  Cl  RbInTlCl
16  Rb  In  Tl  Br  RbInTlBr
17  Rb  In  Tl   I   RbInTlI
24  Cs  In  In  Cl  CsInInCl
25  Cs  In  In  Br  CsInInBr
26  Cs  In  In   I   CsInInI
27  Cs  In  Tl  Cl  CsInTlCl
28  Cs  In  Tl  Br  CsInTlBr
29  Cs  In  Tl   I   CsInTlI